sudo: required
language: minimal

git:
  depth: 2

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/metabolic-ninja
    - IMAGE_TAG=travis-ci-test
    - IMAGE=${IMAGE_REPO}:${IMAGE_TAG}

before_install:
  - echo ${DOCKER_PASSWORD} | docker login -u=decaftravis --password-stdin

install:
  - make setup build

script:
  - make test-travis

before_deploy:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh
  - docker tag ${IMAGE} ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker tag ${IMAGE} ${IMAGE_REPO}:${TRAVIS_BRANCH}
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: "fwGNEIJzK7tlZ9yTj1z/6Xa1Ozo5SK0qSZ0Br757wiTfKHVYKLZZBgnZDlDjlVsSPjFClbuWEsUSa9yh76M80BM3SOnxF8YGr+xeW2dSkyMHPRM8WIGM0Tx3wXU4fn5WW4tH/aHMGtXqh25Dvfm6IAtx3JNXKzC17u6jQT+vrIpKqh1KqnjaJNPSpUhGoE2T8557VICkaN479nAgmvFAn+alAZ2jiZKI672VQcazcy3Yhf+RJGNlyf66M335IbyDiPLnTVd7b47aXIDlR/8N6Ub78COPomPCOqxK0MG2LkNLGsRU6MfcRRkhFpf6F7WHx7srb3qSTC9M8jE0vVgiXT/9N/6n1nL0Bl5QwGfmF++wFGvBBriVPPA4JK12IgIoE3hI+29LnfTMlfv2GuKNH3HQ1bJnoFHqgQedzOG6i2fiQefx8ylcMhDrl6MWY+nqkt7/RjP6Oh/YGt9BmdATxTc1WfDRrWtnAcskAMkCI5925RQbQA8R41QjnO4xNoTG7PdqWkAdVkZ2pqRp1+LahM3Vx5GcX6ktRe4+UroCZBBKOBrPV0HsieuJF+0leV/Ib4c1zFLwI6OonWB6cDXnmJ9FepOHab09hNdV0Gk2hRsu/vM4LhbApxA5UQx7FbNzXaD0aZi+9BVh6JMJuQT+NJPbZbap0SEIuFp+b1L5KAo="
    on_success: change
    on_failure: always
    on_pull_requests: false
