FROM biosustain/cameo-solvers:9cdad976041d
ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt
ADD ./metabolic-ninja/worker.py .
ADD ./metabolic-ninja/utils.py .
ADD ./metabolic-ninja/mongo_client.py .
ADD ./metabolic-ninja/pathway_graph.py .

ENTRYPOINT ["python"]
CMD ["worker.py"]
