FROM biosustain/cobra-cplex:latest

ADD requirements.txt requirements.txt
RUN /bin/bash -c "/opt/conda/envs/python3.4/bin/pip install -r requirements.txt"

ADD ./metabolic-ninja/worker.py .
ADD ./metabolic-ninja/utils.py .
ADD ./metabolic-ninja/mongo_client.py .
ADD ./metabolic-ninja/pathway_graph.py .

ENTRYPOINT ["/opt/conda/envs/python3.4/bin/python"]
CMD ["worker.py"]
