FROM biosustain/cobra-cplex:latest

RUN /bin/bash -c "/opt/conda/envs/python3.4/bin/pip install -r requirements.txt"

VOLUME /metabolic-ninja
WORKDIR /metabolic-ninja

ENTRYPOINT ["/opt/conda/envs/python3.4/bin/python"]
CMD ["worker.py"]
