apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: metabolic-ninja-legacy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # websocket support
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  tls:
  - hosts:
    - api.dd-decaf.eu
    secretName: decaf-tls
  rules:
  - host: api.dd-decaf.eu
    http:
      paths:
      - path: /pathways
        backend:
          serviceName: metabolic-ninja-legacy
          servicePort: 80
