kind: Service
apiVersion: v1
metadata:
  name: metabolic-ninja-legacy
spec:
  selector:
    app: metabolic-ninja
    env: legacy
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: 8000
