kind: Service
apiVersion: v1
metadata:
  name: metabolic-ninja-production
  annotations:
    prometheus.io/probe: "true"
spec:
  selector:
    app: metabolic-ninja
    env: production
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: 8000

---

kind: Service
apiVersion: v1
metadata:
  name: metabolic-ninja-staging
  annotations:
    prometheus.io/probe: "true"
spec:
  selector:
    app: metabolic-ninja
    env: staging
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: 8000
